# Generated by Django 4.0.6 on 2022-08-15 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=500)),
                ('uploaded_file', models.FileField(upload_to='')),
                ('file_size', models.IntegerField(null=True)),
                ('zip_file', models.FileField(upload_to='')),
                ('saved_file', models.FileField(upload_to='')),
                ('saved_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_on'],
            },
        ),
    ]
